format = """
[îƒŠ ](#FFFFFF)\
[ ](bg:#00797d)\
[ï…¹ ](bg:#00797d fg:#FFFFFF)\
$username\
[îƒˆ](bg:#008c9a fg:#00797d)\
[ ï¼](bg:#008c9a fg:#FFFFFF)\
$directory\
[îƒˆ](fg:#008c9a bg:#00a1ae)\
$git_branch\
$git_status\
[îƒˆ](fg:#00a1ae bg:#00c5cf)\
$c\
$golang\
$java\
$nodejs\
$python\
$rust\
[îƒˆ](fg:#00c5cf bg:#FFFFFF)\
$time\
[îƒˆ ](fg:#FFFFFF)\
$fill\
$cmd_duration\
$hostname\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "fg:#FFFFFF bg:#00797d"
style_root = "fg:#FFFFFF bg:#00797d"
format = '[$user ](bold $style)'
disabled = false

[cmd_duration]
min_time = 1
format = 'took [$duration](bold #00FFFF) on'

[character]
success_symbol = '[ï](bold green) '
error_symbol = '[îª‡](bold red) '

[hostname]
ssh_only = false
format = ' [$hostname](#00a1ae) '
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "fg:#00FFFF bg:#008c9a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ïœ˜ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ïœ˜ " = " ïœ˜ï„ª "

[fill]
symbol = ' '

[c]
symbol = "î˜"
style = "bg:#00c5cf"
format = '[ $symbol ]($style)'

[docker_context]
symbol = "î° "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = "ï˜"
style = "fg:#002545 bg:#00a1ae"
format = '[ $symbol $branch ]($style)'


[git_status]
style = "fg:#00FFFF bg:#00a1ae"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£–"
modified = "ï„ "
staged = '[++\($count\)](fg:#002545 bg:#00a1ae)'
renamed = "ïª¶"
deleted = "ï€”"
format = '[$all_status$ahead_behind](bold $style)'

[golang]
symbol = "go"
style = "fg:#002545 bg:#00c5cf"
format = '[ $symbol ]($style)'

[java]
symbol = "î‰–"
style = "fg:#002545 bg:#00c5cf"
format = '[ $symbol ]($style)'

[nodejs]
symbol = "îœ˜"
style = "fg:#002545 bg:#00c5cf"
format = '[ $symbol ]($style)'

[python]
# Display the version of python from inside a local venv.
#
# Note this will only work when the venv is inside the project and it will only
# work in the directory that contains the venv dir but maybe this is ok?
symbol = 'îˆµ '
style = "fg:#002545 bg:#00c5cf"
format = '[ $symbol ]($style)'

[rust]
symbol = "îš‹"
style = "fg:#002545 bg:#00c5cf"
format = '[ $symbol ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#002545 bg:#FFFFFF"
format = '[ ï€— $time ]($style)'